In [1]:
import torch

## Initialization

In [2]:
target = torch.randn(1, 1)
input = torch.randn(1, 2)
network = torch.nn.Linear(2, 1)
optimizer = torch.optim.SGD(network.parameters(), lr=0.01)
optimizer.zero_grad()

In [3]:
print(network.weight)
print(network.bias)

Parameter containing:
tensor([[-0.0913, -0.6495]], requires_grad=True)
Parameter containing:
tensor([-0.5691], requires_grad=True)


In [4]:
input

tensor([[0.2299, 0.0497]])

In [5]:
target

tensor([[-0.0990]])

## Foward

In [6]:
input @ network.weight.T + network.bias

tensor([[-0.6224]], grad_fn=<AddBackward0>)

In [7]:
u = network(input)
u

tensor([[-0.6224]], grad_fn=<AddmmBackward>)

In [8]:
with torch.no_grad():
    d = (u + 1.0 - target)
    d.requires_grad = False
d

tensor([[0.4766]])

In [13]:
d.backward() # torch.Tensor(d.shape))

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [14]:
d.grad

In [15]:
u.grad

In [16]:
network.weight.grad

## Forcing grads

In [17]:
u.backward(gradient=torch.randn(1, 1))

In [18]:
u.grad

In [19]:
network.weight.grad

tensor([[-0.0196, -0.0042]])

## Inventing grads

In [12]:
grad = torch.randn(1, 1)
grad

tensor([[0.2451]])

In [14]:
d.grad = grad
d.grad

tensor([[0.2451]])

In [7]:
loss = ((d)**2).sum()
loss

tensor(11.3316, grad_fn=<SumBackward0>)

## Trying to force grads

In [8]:
loss.grad

In [9]:
loss.grad = grad.sum()
loss.grad

tensor(0., grad_fn=<SumBackward0>)

In [10]:
loss

tensor(11.3316, grad_fn=<SumBackward0>)

In [11]:
loss.backward()
loss

tensor(11.3316, grad_fn=<SumBackward0>)

## Checking if things happened

In [12]:
print(network.weight[0, 0])

tensor(-0.0332, grad_fn=<SelectBackward>)


In [13]:
optimizer.step()
print(network.weight[0, 0]) #works (it is changed)

tensor(-0.0438, grad_fn=<SelectBackward>)


In [17]:
network.weight.grad[0, 0] = 100
optimizer.step()
print(network.weight[0, 0]) #works (it is changed)

tensor(-2.0550, grad_fn=<SelectBackward>)


In [18]:
network.weight.grad = torch.randn(10, 20)
optimizer.step()
print(network.weight[0, 0]) #works (it is changed)

tensor(-2.0587, grad_fn=<SelectBackward>)
